# Generated by Django 6.1.1 on 2026-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
